module.exports = {
    APP_NAME: `NZAMY`,
    PORT: process.env.APP_PORT,
    DB_URL: process.env.PROD_DB_URL,
    //DB_URL: process.env.DB_URL,
    SUPPORT_NUMBER: '+201555415331',
    GENDER: ['MALE', 'FEMALE'],
    ROLES: ['OWNER', 'DOCTOR', 'STAFF'],
    TYPES: ['EMPLOYEE', 'ADMIN'],
    SPECIALITIES_TYPES: ['MAIN', 'SUB'],
    EMAIL: {
        APP_MAIL: 'raayaeg@gmail.com',
        APP_MAIL_PASSWORD: process.env.APP_MAIL_PASSWORD,
        APP_MAIL_SERVICE: 'gmail'
    },
    SALT_ROUNDS: Number.parseInt(process.env.SALT_ROUNDS),
    SECRET_KEY: process.env.SECRET_KEY,
    NOTIFICATION_EMAIL: 'omarredaelsayedmohamed@gmail.com',
    PAGINATION_LIMIT: 10,    
    LANGUAGES: ['en', 'ar'],
    TIME_UNIT: ['day', 'week', 'month'],
    WEEK_DAYS: ['SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY'],
    PAYMENT_METHODS: ['CASH', 'CARD'],
    TRANSACTION_TYPE: ['PURCHASE', 'SALE', 'RETURN', 'ADJUSTMENT', 'DAMAGE', 'THEFT'],
    TABLE_STATUS: ['AVAILABLE', 'OCCUPIED', 'RESERVED', 'IN-PROGRESS', 'COMPLETED'],
    GROUP_STATUS: ['ACTIVE', 'INACTIVE', 'COMPLETED'],
    REFER_METHODS: ['FRIEND', 'SOCIAL-MEDIA', 'ADVERTISEMENT', 'WORD-OF-MOUTH', 'SCHOOL', 'OTHER'],
    SUBSCRIPTION_STATUS: ['ACTIVE', 'EXPIRED', 'CANCELLED'],
    ATTENDANCE_STATUS: ['PRESENT', 'ABSENT', 'EXCUSED'],
    SUBMISSION_STATUS: ['PENDING', 'SUBMITTED'],
    EXAM_TYPES: [
        "WRITTEN",
        "PRACTICAL",
        "ORAL",
        "PROJECT-BASED",
        "ONLINE/DIGITAL",
        "PRACTICAL PERFORMANCE",
        "OPEN BOOK",
        "COMPREHENSIVE"
    ],
    EXAM_SUBTYPES: [
        "ESSAY",
        "SHORT ANSWER",
        "MULTIPLE CHOICE",
        "TRUE/FALSE",
        "FILL IN THE BLANKS",
        "LAB",
        "DEMONSTRATION",
        "VIVA VOCE (ORAL EXAM)",
        "PRESENTATION",
        "RESEARCH PROJECT",
        "GROUP PROJECT",
        "QUIZ",
        "TIMED ONLINE TEST",
        "SKILL TEST",
        "FIELDWORK",
        "OPEN BOOK",
        "TAKE-HOME",
        "MID-TERM",
        "FINAL"
    ],
    ACADEMIC_YEARS: [
        "KG1",
        "KG2",
        "GRADE 1",
        "GRADE 2",
        "GRADE 3",
        "GRADE 4",
        "GRADE 5",
        "GRADE 6",
        "GRADE 7",
        "GRADE 8",
        "GRADE 9",
        "GRADE 10",
        "GRADE 11",
        "GRADE 12",
        "UNIVERSITY"
    ],
    PRINTER_IP: 'tcp://192.168.123.100'
}