module.exports = {
    APP_NAME: `RA'AYA-SMS`,
    PORT: process.env.APP_PORT,
    URL: 'https://raaya-sms.web.app',
    //URL: 'http://localhost:5173',
    DB_URL: process.env.PROD_DB_URL,
    //DB_URL: process.env.DB_URL,
    TELEGRAM_WEBHOOK: `https://app-tltqayhmna-uc.a.run.app/bot${process.env.TELEGRAM_TOKEN}`,
    TELEGRAM_BOT_URL: `https://t.me/daleeliBot`,
    SUPPORT_NUMBER: '+201555415331',
    GENDER: ['MALE', 'FEMALE'],
    TYPES: ['EMPLOYEE', 'ADMIN', 'OWNER'],
    EMAIL: {
        APP_MAIL: 'raayaeg@gmail.com',
        APP_MAIL_PASSWORD: process.env.APP_MAIL_PASSWORD,
        APP_MAIL_SERVICE: 'gmail'
    },
    SALT_ROUNDS: Number.parseInt(process.env.SALT_ROUNDS),
    SECRET_KEY: process.env.SECRET_KEY,
    NOTIFICATION_EMAIL: 'omarredaelsayedmohamed@gmail.com',
    PAGINATION_LIMIT: 10,    
    LANGUAGES: ['en', 'ar'],
    TIME_UNIT: ['day', 'week', 'month'],
    WEEK_DAYS: ['SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY'],
    PAYMENT_METHODS: ['CASH', 'CARD', 'E-WALLET'],
    TRANSACTION_TYPE: ['PURCHASE', 'SALE', 'RETURN', 'ADJUSTMENT', 'DAMAGE', 'THEFT'],
    GROUP_STATUS: ['ACTIVE', 'INACTIVE', 'COMPLETED'],
    REFER_METHODS: ['FRIEND', 'SOCIAL-MEDIA', 'ADVERTISEMENT', 'WORD-OF-MOUTH', 'SCHOOL', 'OTHER'],
    SUBSCRIPTION_STATUS: ['ACTIVE', 'EXPIRED', 'CANCELLED'],
    ATTENDANCE_STATUS: ['PRESENT', 'ABSENT', 'EXCUSED'],
    SUBMISSION_STATUS: ['PENDING', 'SUBMITTED', 'UNSUBMITTED'],
    EXAM_TYPES: [
        "WRITTEN",
        "PRACTICAL",
        "ORAL",
        "PROJECT-BASED",
        "ONLINE/DIGITAL",
        "PRACTICAL PERFORMANCE",
        "OPEN BOOK",
        "COMPREHENSIVE",
        "QUIZ",
        "MID-TERM",
        "FINAL",
        "QUIZ"
    ],
    EXAM_SUBTYPES: [
        "ESSAY",
        "SHORT ANSWER",
        "MULTIPLE CHOICE",
        "TRUE/FALSE",
        "FILL IN THE BLANKS",
        "LAB",
        "DEMONSTRATION",
        "ORAL",
        "PRESENTATION",
        "RESEARCH PROJECT",
        "GROUP PROJECT",
        "TIMED ONLINE TEST",
        "SKILL TEST",
        "FIELDWORK",
        "OPEN BOOK",
        "TAKE-HOME"
    ],
    ACADEMIC_YEARS: [
        "GRADE 1 KINDERGARTEN",
        "GRADE 2 KINDERGARTEN",
        "GRADE 1 PRIMARY",
        "GRADE 2 PRIMARY",
        "GRADE 3 PRIMARY",
        "GRADE 4 PRIMARY",
        "GRADE 5 PRIMARY",
        "GRADE 6 PRIMARY",
        "GRADE 1 PREPARATORY",
        "GRADE 2 PREPARATORY",
        "GRADE 3 PREPARATORY",
        "GRADE 1 SECONDARY",
        "GRADE 2 SECONDARY",
        "GRADE 3 SECONDARY",
        "GRADE 1 UNIVERSITY",
        "GRADE 2 UNIVERSITY",
        "GRADE 3 UNIVERSITY",
        "GRADE 4 UNIVERSITY"
    ],
    CHAPTERS: [
        'CHAPTER 1',
        'CHAPTER 2',
        'CHAPTER 3',
        'CHAPTER 4',
        'CHAPTER 5',
        'CHAPTER 6',
        'CHAPTER 7',
        'CHAPTER 8',
        'CHAPTER 9',
        'CHAPTER 10'
    ],
    PRINTER_IP: 'tcp://192.168.123.100'
}